// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mkakninypgzugqbqjbmy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1rYWtuaW55cGd6dWdxYnFqYm15Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMzM0NTcsImV4cCI6MjA2MjgwOTQ1N30.CezumGedJVM4IWdn7LaN1UDg805KwwNANyTSS1uWMIw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);